title: Wesley DeMontigny
description: Probabilistic modeling, computational biology, and scientific software
theme: minima
plugins:
 - jekyll-feed
header_pages:
 - writing/index.html
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  parse_block_html: true
